const mongoose=require('mongoose')
const patientSchema=new mongoose.Schema({
    patientid:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User'
    },
    address:{
        district:String,
        taluk:String,
        state:String,
        street_name:String,
        locality:String,
    },
    caretaker:{
        name:String,
        phoneno:Number
    },
    startdate:Date, //notip
    enddate:Date, //notip
    status:String,
    comorbidity:{
        cancer:Boolean,
        ckd:Boolean,
        copd:Boolean,
        dementia:Boolean,
        diabetes:Boolean,
        down_syndrome:Boolean,
        hear_tconditions:Boolean,
        hiv:Boolean,
        immunocompromised_state:Boolean,
        liver:Boolean,
        overweight_obesity:Boolean,
        pregnancy:Boolean,
        thalassemia:Boolean,
        smoker:Boolean,
        transplant:Boolean,
        stroke:Boolean,
    },
    issymptomatic:Boolean,
    symptons:{
        fever:Boolean,
        body_temperature:Boolean,
        chills:Boolean,
        cough:Boolean,
        shortness_of_breath:Boolean,
        fatigue:Boolean,
        muscle_body_aches:Boolean,
        headache:Boolean,
        taste_smell_loss:Boolean,
        sore_throat:Boolean,
        runny_nose:Boolean,
        nausea:Boolean,
        dairrhea:Boolean,
    },
    spo2:Number,
    dailydata:[{
        day:Number,
        time:String,
        spo2:Number,
        fever:String,
        body_temperature:Number,
        chills:String,
        cough:String,
        fatigue:String,
        muscle_body_aches:String,
        headache:String,
        taste_smell_loss:String,
        sore_throat:String,
        runny_nose:String,
        nausea:String,
        dairrhea:String,
        review:String
    }], //noti/p
    doctorid:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Doctor'
    },
    //noti/p
    districtid:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User'
    },
    district:String
})
module.exports=new mongoose.model('Patient',patientSchema)